# -*- coding: utf-8 -*-
"""TEST-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YJUQ5w3Qhe7w6cDmrRzjcZPmJNbx8NS
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv("dataset_v1.csv")
data

data.isnull().sum()

data.drop(columns=["Unnamed: 0"], inplace = True)
data

imputer = SimpleImputer(missing_values=pd.NA, strategy="constant", fill_value=0)

imputer.fit(data[["Present_weather"]])
data["Present_weather"] = imputer.transform(data[["Present_weather"]])

imputer.fit(data[["Past_weather"]])
data["Past_weather"] = imputer.transform(data[["Past_weather"]])

imputer.fit(data[["Area_threshold"]])
data["Area_threshold"] = imputer.transform(data[["Area_threshold"]])

imputer.fit(data[["River"]])
data["River"] = imputer.transform(data[["River"]])

imputer = SimpleImputer(missing_values=pd.NA, strategy="mean")

imputer.fit(data[["Rainfall"]])
data["Rainfall"] = imputer.transform(data[["Rainfall"]])

imputer.fit(data[["Humidity"]])
data["Humidity"] = imputer.transform(data[["Humidity"]])

imputer.fit(data[["Tmax"]])
data["Tmax"] = imputer.transform(data[["Tmax"]])

imputer.fit(data[["Tmin"]])
data["Tmin"] = imputer.transform(data[["Tmin"]])

imputer.fit(data[["Tavg"]])
data["Tavg"] = imputer.transform(data[["Tavg"]])

imputer.fit(data[["Wind_spd"]])
data["Wind_spd"] = imputer.transform(data[["Wind_spd"]])

imputer.fit(data[["Cloud_amt"]])
data["Cloud_amt"] = imputer.transform(data[["Cloud_amt"]])

imputer.fit(data[["max_wl"]])
data["max_wl"] = imputer.transform(data[["max_wl"]])

imputer.fit(data[["min_wl"]])
data["min_wl"] = imputer.transform(data[["min_wl"]])

imputer.fit(data[["avg_wl"]])
data["avg_wl"] = imputer.transform(data[["avg_wl"]])

imputer = SimpleImputer(missing_values=pd.NA, strategy="most_frequent")

imputer.fit(data[["Wind_dir"]])
data["Wind_dir"] = imputer.transform(data[["Wind_dir"]])

data.to_csv('dataset_v2.csv')